apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: svc-test
  name: svc-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: svc-test
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        resources: {}
status: {}
