apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker
    spec:
      containers:
      - image: pandaacademy/worker:1.0
        name: worker
        resources: {}
        env:
          - name: POSTGRES_USER
            value: "panda"
          - name: POSTGRES_PASSWORD
            value: "panda"
          - name: DB_HOST
            value: "db-svc.database"
          - name: REDIS_HOST
            value: "redis-svc.database"
status: {}
